ALTER SESSION SET CURRENT_SCHEMA = TABSDATA_USER;
ALTER SESSION SET CONTAINER=ORCLPDB1;

INSERT INTO TABSDATA_USER.customers (seq, first, last, age, state, zip)
VALUES (10, 'Alice', 'Smith', 30, 'CA', '90210');

COMMIT;

DELETE FROM TABSDATA_USER.customers
WHERE SEQ = 4;

COMMIT;

UPDATE TABSDATA_USER.customers
SET AGE = AGE + 1
WHERE SEQ = 7;

COMMIT;

SELECT * FROM TABSDATA_USER.customers;
